#!/usr/bin/env python
import logging

import colorama
import coloredlogs
import verboselogs

from src.main.python import main

colorama.init()
verboselogs.install()
coloredlogs.install()

_logger = logging.getLogger('defeasible')

if __name__ == '__main__':
    main()
    _logger.verbose('Done.')
